### ISSUE TITLE
[BUG] Grouped PCB Items cause an assert in `~BOARD_ITEM()`

### ISSUE THREAD

**Issue by Sypaq-MadMan** [INTI-CMNB/KiBot#449] opened 2023-06-08 06:30 UTC
Not an expert in KiCAD/KiBot so please correct me if any of this is wrong. This also might be more relevant in the KiCAD repo however this is the scenario in which I can reproduce the issue easily.

**Describe the bug**
Grouped PCB Items cause an assertion in the deconstructor of `~BOARD_ITEM()` when running KiBot.
[./pcbnew/board_item.cpp](https://gitlab.com/kicad/code/kicad/-/blob/7.0/pcbnew/board_item.cpp?ref_type=heads#L40)(39): `assert "m_group == nullptr" failed in ~BOARD_ITEM()`

**To Reproduce**
Build and Run this [test_project.zip](https://github.com/INTI-CMNB/KiBot/files/11684591/test_project.zip) docker test project using the follow commands.

Build: ``` docker build -f Dockerfile --force-rm=true -t test_kibot `pwd` ```

Run: ``` docker run --rm -it -v `pwd`:/data test_kibot ```

If you want to debug the image without running the gen.sh script then just pass in `--entrypoint /bin/bash` with the run command.

**Expected behavior**
Same as working example, No assertions

**Screenshots**
![image](https://github.com/INTI-CMNB/KiBot/assets/81274690/0a6cdb38-6def-449c-989d-9d1612a9d5cc)

**Environment (please complete the following information):**
Where are you running KiBot:
- Earth->Australia
- Docker using `kicad7_auto:latest` image from `ghcr.io/inti-cmnb`
- Using Ubuntu 22.04.2 LTS

**Additional context**
- Issue only presented after upgrading to KiCAD7 from KiCAD6.
- Test project was generated using KiCAD7 on Ubuntu, I also tried generating the project using KiCAD 7 on Windows 10.
- See my [Discord post](https://discord.com/channels/502708194179809281/813247718512132157/1115798511229866126
) for different things I tried when searching for the issue.
- Log Files from both [log_working_build_1.txt](https://github.com/INTI-CMNB/KiBot/files/11684787/log_test_project_build_1.txt)  and [log_test_project_broken_build_2.txt](https://github.com/INTI-CMNB/KiBot/files/11684793/log_test_project_build_2.txt).
- Note: I use the nomenclature working/broken this is probably not completely accurate.

**Comment by set-soft** [comment] 2023-06-08 12:33
Hi @Sypaq-MadMan !

Don't worry about it, is just a silly message. The problem is triggered by the following code:

```python
import pcbnew

board = pcbnew.LoadBoard('test_project_broken.kicad_pcb')
for m in board.GetFootprints():
    m.GetFpPadsLocalBbox()
```

This function is implemented like this:

```C++
BOX2I FOOTPRINT::GetFpPadsLocalBbox() const
{
    BOX2I bbox;

    // We want the bounding box of the footprint pads at rot 0, not flipped
    // Create such a image:
    FOOTPRINT dummy( *this );

    dummy.SetPosition( VECTOR2I( 0, 0 ) );
    dummy.SetOrientation( ANGLE_0 );

    if( dummy.IsFlipped() )
        dummy.Flip( VECTOR2I( 0, 0 ), false );

    for( PAD* pad : dummy.Pads() )
        bbox.Merge( pad->GetBoundingBox() );

    dummy.SetParent( nullptr );

    return bbox;
}
```

The problem here is the auxiliary object: dummy
It is created using the current component as base, including the group.
The destructor seems to complain that the object still part of a group when destroyed. Which isn't really important.

**Comment by set-soft** [comment] 2023-06-08 12:48
I filled a KiCad bug about it: https://gitlab.com/kicad/code/kicad/-/issues/14909

Lets see the developers opinion. 

I'm closing it here because the problem is out of KiBot scope and the message seems to be innocuous.

**Closed by set-soft** 2023-06-08 12:48 UTC
Labels: question

**Comment by Sypaq-MadMan** [comment] 2023-06-08 21:26
Hi @set-soft,

Thanks for the reply and moving the issue to the appropriate project. 

I'd be keen to see what the developers say on your issue which looks a fair bit more refined than my explanation. I do agree the message seems to be innocuous, which is what I concluded after I looked at both datapacks generated in my example, that appear to be identical.
