### ISSUE TITLE
Variant with Rotation Filter Not Including All Parts in Pick and Place File

### ISSUE THREAD

**Issue by daveismith** [INTI-CMNB/KiBot#55] opened 2021-03-03 13:09 UTC
Thanks for all the hard work on this project, it's wonderful to be able to integrate it as part of a github action to help check PRs and automatically keep generated artifacts up to date on a commit.

A project I'm working on has a board with variants which we want to produce the JLCPCB fab files for. You can see the project and associated config file at https://github.com/daveismith/index/tree/feature/128-kibot-variants/feeder/pcb/mobo. It's run in github actions on each commit and produces uploaded artifacts as part of this action: https://github.com/daveismith/index/actions/runs/616280571. The one of interest is the feeder_mobo_output which contains two variants. One is the default and the other is specified with the key VCNT2020. Instead of running two separate runs, I use the config to output separate schematic, bom and cpl (pick and place) files for the variant. The schematic and the bom correctly pick up the variants, but when I look at my CPL file for the variant it's missing U2.

I've attached the two versions of the schematics, bom and cpl files as well as my config. The BOM and CPL files have been renamed to TXT to allow attachment. I'm hoping I've just missed something in the documentation.

[Schematic.pdf](https://github.com/INTI-CMNB/KiBot/files/6076135/Schematic.pdf)
[Schematic_vcnt2020.pdf](https://github.com/INTI-CMNB/KiBot/files/6076134/Schematic_vcnt2020.pdf)

[mobo_bom_jlc.csv.txt](https://github.com/INTI-CMNB/KiBot/files/6076146/mobo_bom_jlc.csv.txt)
[mobo_bom_jlc_vcnt2020.csv.txt](https://github.com/INTI-CMNB/KiBot/files/6076149/mobo_bom_jlc_vcnt2020.csv.txt)

[mobo_cpl_jlc.csv.txt](https://github.com/INTI-CMNB/KiBot/files/6076141/mobo_cpl_jlc.csv.txt)
[mobo_cpl_jlc_vcnt2020.csv.txt](https://github.com/INTI-CMNB/KiBot/files/6076143/mobo_cpl_jlc_vcnt2020.csv.txt)

[config.kibot.yaml.txt](https://github.com/INTI-CMNB/KiBot/files/6076150/config.kibot.yaml.txt)

**Comment by set-soft** [comment] 2021-03-12 19:14
Hi @daveismith !

Sorry for the delay. I'm working on integrating KiCost and GitHub notifications are sloppy.

Anyways, the problem is that your VCNT2020 component is marked as THT in the PCB, not as SMD. Your config says `only_smd: true` so KiBot is excluding it.
I edited the PCB and marked it as SMD and got it listed.

That's all

**Closed by set-soft** 2021-03-12 19:14 UTC
Labels: question
