### ISSUE TITLE
[HOW] DRC exlusiones stoped working 

### ISSUE THREAD

**Issue by MarkusSBS** [INTI-CMNB/KiBot#653] opened 2024-08-22 12:00 UTC
DRC stoped working for me and my jobs are failing.

Jobs for repositorys worked fine 2 monthe ago and without any changes fail if i rerun the job.

I have testet it with kicad 7 and i migrated a projekt  to kicad 8 and have the same result.

is there a migration step i missed? I have no errors and some exlusiones in my local kicad DRC scan but all exlusions are reportet as errors.

**Comment by MarkusSBS** [comment] 2024-08-22 12:22
here my kibot test projekt. I just rerun the pipeline: 
![image](https://github.com/user-attachments/assets/ead5b910-f06c-4dfc-85e7-67239d24fbd0)

**Comment by set-soft** [comment] 2024-08-22 13:08
> DRC stoped working for me and my jobs are failing.
> 
> Jobs for repositorys worked fine 2 monthe ago and without any changes fail if i rerun the job.

Is hard to know the reason with no information about versions involved.

> I have testet it with kicad 7 and i migrated a projekt to kicad 8 and have the same result.
> 
> is there a migration step i missed? 

When migrating to KiCad 8 you should also migrate from *run_drc* to *drc*, a warning explains it. The *drc* preflight is cleaner and uses a fast mechanism.

> I have no errors and some exlusiones in my local kicad DRC scan but all exlusions are reportet as errors.

DRC exclusions are stored in the project file (*kicad_pro*), they looks like this:

```
      "drc_exclusions": [
        "clearance|176385001|79614999|7e023245-2c2b-4e2b-bfb9-5d35176e88f2|666713b0-70f4-42df-8761-f65bc212d03b",
        "invalid_outline|165100000|80645000|e6d8b5bb-6f41-4222-9a89-b8a6280d0752|00000000-0000-0000-0000-000000000000",
        "silk_over_copper|153440000|84620000|3f5fe6b7-98fc-4d3e-9567-f9f7202d1455|f4f99e3d-7269-4f6a-a759-16ad2a258779"
```

They are verified in the regression tests, so I need an example where they fail to work.

**Comment by MarkusSBS** [comment] 2024-08-22 13:48
drc_exclusions are included in the projekt file.

docker image ist image:
  name:  ghcr.io/inti-cmnb/kicad7_auto_full:dev

I will send you a zip of the test repo

**Comment by set-soft** [comment] 2024-08-23 10:06
Hallo @MarkusSBS !

This was related to a known KiCad bug that we had a workaround, but wasn't applied at all the needed places. In your particular case the *set_text_variables* triggered the issue.

Now should be fixed.

**Closed by set-soft** 2024-08-23 10:06 UTC
Labels: kicad_bug

**Comment by MarkusSBS** [comment] 2025-07-02 12:21
i think there is something broken again but only courtyards_overlap exclusions are ignord.

It breaks also for old DRC runs if i try to rerun it with the current docker image.

  name:  ghcr.io/inti-cmnb/kicad8_auto_full:dev

it was just a small change i want so export of an older projekt

**Comment by set-soft** [comment] 2025-07-02 12:32
Hi @MarkusSBS !
I need a test case, exclusions are tested by the regression tests and the test case is passing.
So I need a case where it doesn't. 
The simplest way is to create a toy project with the DRC error you can't exclude.

**Comment by MarkusSBS** [comment] 2025-07-02 13:51
i send you an test projekt

**Comment by set-soft** [comment] 2025-07-02 14:15
Hi @MarkusSBS !
I tried your project using the KiCad 9.0.2 in my system and I got 3 violations, the same I got using KiBot.
I manually excluded them to get 0 and running KiBot I get 0.
I think you are using KiCad != 9.0.2 and KiCad exclusions are incompatible. Which KiCad are you using?

**Comment by MarkusSBS** [comment] 2025-07-02 14:18
it is an older kicad8 projekt i have not upgradet to 9.
the docker image is ghcr.io/inti-cmnb/kicad8_auto_full:dev

**Comment by MarkusSBS** [comment] 2025-07-02 14:24
normaly i will upgrade to a newer version but for old projekt there is sometimes no kicad involved on user side in generating a new dataset. for example a different variant so it would by nice to have a working kicad 8 version without changing and fixing the yaml config for the latest version. Work in progress projekts will migrate to the newer version with no problem

**Comment by set-soft** [comment] 2025-07-02 14:59
Ok, but is a similar situation, I started the docker image and inside I first executed KiBot, got:

```
ERROR:2 DRC errors detected (kibot.pre_drc - pre_drc.py:151)
ERROR:(courtyards_overlap) Courtyards overlap
    @(176.0 mm, 130.0 mm): Footprint R12
    @(176.0 mm, 130.0 mm): Footprint C1
    Check: Violations (kibot.pre_drc - pre_drc.py:166)
ERROR:(courtyards_overlap) Courtyards overlap
    @(254.8 mm, 123.4 mm): Footprint TP102
    @(258.5 mm, 120.0 mm): Footprint TP101
    Check: Violations (kibot.pre_drc - pre_drc.py:166)
ERROR:DRC errors: 2 (kibot.gs - gs.py:901)
```

So I executed KiCad and got: 

![Image](https://github.com/user-attachments/assets/0b49434f-4fdf-422f-9ded-9cad48c846ad)

I ignored them, saved and when executing KiBot I got 0 violations.

KiCad in the docker image is:

![Image](https://github.com/user-attachments/assets/fcb432f0-262e-42e6-8b65-9fc2052422d9)

Your project says:

```
        "courtyards_overlap|175541285|129070001|978ca26f-2668-4f48-8de8-fd59192c9a05|e2a24c34-a997-4ecc-881f-4e6abd966b00",
        "courtyards_overlap|254476552|118808850|9f726ca9-5002-480b-ba89-adc719147636|aa441d2b-1def-4007-bdd4-e939d6260256",
```

After manually adding them again reads:

```
       "courtyards_overlap|175545339|129075000|978ca26f-2668-4f48-8de8-fd59192c9a05|e2a24c34-a997-4ecc-881f-4e6abd966b00",
       "courtyards_overlap|254476903|118813842|9f726ca9-5002-480b-ba89-adc719147636|aa441d2b-1def-4007-bdd4-e939d6260256",
```

A few µm of difference, so this is the usual rounding errors KiCad introduces from version to version.
Can you use the same KiCad version?

**Comment by MarkusSBS** [comment] 2025-07-02 15:06
i will test it 

these rounding issue sounds realistic but still sucks a little bit on the kicad side by breaking older projekt if there is an update.

**Comment by set-soft** [comment] 2025-07-08 11:17
Remember you can add KiBot filters, I know having the same thing filtered twice is annoying, but if you use different KiCad versions is the only solution. Which exact version are you using?
