### ISSUE TITLE
[BUG] navigate_result generator crashes

### ISSUE THREAD

**Issue by laenzlinger** [INTI-CMNB/KiBot#742] opened 2024-12-15 21:19 UTC
Fill as much as you can, remove the rest

**Describe the bug**
Since a while, i get the following error on the CI pipeline

```
- 'Web page to browse the results' (basic_navigate_results) [navigate_results]
Traceback (most recent call last):
  File "/usr/bin/kibot", line 33, in <module>
    sys.exit(load_entry_point('kibot==1.8.2', 'console_scripts', 'kibot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/kibot/__main__.py", line 598, in main
    generate_outputs(args.target, args.invert_sel, args.skip_pre, args.cli_order, args.no_priority,
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 678, in generate_outputs
    _generate_outputs(targets, invert, skip_pre, cli_order, no_priority, dont_stop)
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 668, in _generate_outputs
    run_output(out, dont_stop)
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 569, in run_output
    out.run(get_output_dir(out.dir, out))
  File "/usr/lib/python3/dist-packages/kibot/out_base.py", line 209, in run
    self.options.run(target)
  File "/usr/lib/python3/dist-packages/kibot/out_navigate_results.py", line 735, in run
    o_tree = self.create_tree()
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/kibot/out_navigate_results.py", line 632, in create_tree
    self.add_to_tree(c, pre, o_tree)
  File "/usr/lib/python3/dist-packages/kibot/out_navigate_results.py", line 321, in add_to_tree
    cat = cat.split('/')
          ^^^^^^^^^
AttributeError: type object 'Optionable' has no attribute 'split'
Error: Process completed with exit code 1.
```

**To Reproduce**
Command line options passed to KiBot, configuration files (.kibot.yaml), PCB/Schematic example to reproduce it 

see https://github.com/pedalboard/pedalboard-hw/blob/main/pedalboard-hw.kibot.yaml

**Expected behavior**
html site should be generated

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? ( `GitHub`)
- Using a docker image? (`ghcr.io/inti-cmnb/kicad8_auto_full:latest`)

**Comment by laenzlinger** [comment] 2024-12-15 22:11
The problem is related to the new drc/erc preflight settings.
When using the old `run_erc` and `run_erc` preflight, it works.

**Comment by set-soft** [comment] 2024-12-16 14:01
Thanks for reporting.
The problem is now fixed on *dev*. As a workaround you can use something like:

```yaml
  erc:
    enabled: true
```

The problem was when using the boolean mechanism, in this case the category wasn't initialized and it was needed by the Navigate Results output.

**Closed by set-soft** 2024-12-16 14:01 UTC
