### ISSUE TITLE
[BUG] ${ISSUE_DATE} and set_text_variables: not working as expected 

### ISSUE THREAD

**Issue by MarkusSBS** [INTI-CMNB/KiBot#361] opened 2023-01-09 14:54 UTC
**Describe` the bug**
For the schematic set_text_variables works as expected and the variables are changed but ${ISSUE_DATE} is empty.
For the board it is the exact opposite set_text_variables does not work at all but ${ISSUE_DATE} is replaced by the current date.

Config should be the same for both 

**To Reproduce**

```
# Example KiPlot config file
kiplot:
  version: 1

preflight:
  run_erc: true
  update_xml: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false
  set_text_variables:
    - name: 'SBS_Prj_Reviewer'
      command: 'git log -1 --pretty=format:"%cn"'
    - name: 'SBS_Prj_Creator'
      command: 'git log -1 --pretty=format:"%an"'

global:
  drc_exclusions_workaround: true
  units: 'millimeters'
  date_time_format: '%d.%m.%Y'
#   kiauto_time_out_scale: 2


outputs:
  - name: 'print_sch'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: Schematic
    options:
      output: "%v_%p_Rev%r-%i_%D.%x"
      
  - name: 'gerbers'
    comment: "Gerbers for the board house"
    type: gerber
    dir: Gerbers
    options:
      # generic layer options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      output: "%v_%p_Rev%r-%i_%D.%x"
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      disable_aperture_macros: true
      line_width: 0.1
      uppercase_extensions: true
      subtract_mask_from_silk: true
      inner_extension_pattern: '.g%n'
      edge_cut_extension: '.gml'
    layers:
      - 'copper'
      - 'F.SilkS'
      - 'B.SilkS'
      - 'F.Mask'
      - 'B.Mask'
      - 'Edge.Cuts'
      - 'F.Paste'
      - 'B.Paste'

  - name: 'drill'
    comment: "Drill files"
    type: excellon
    dir: dril
    options:
      pth_and_npth_single_file: false
      pth_id: '-PTH'
      npth_id: '-NPTH'
      output: "%v_%p_Rev%r-%i_%D.TXT"
      
      
  - name: 'print_pcb_pdf'
    comment: "PDF for the PCB"
    type: pcb_print
    dir: PCB_Docu
    options:
      #svg_precision: 6
      realistic_solder_mask: false
      force_edge_cuts: true
      keep_temporal_files: false
      #enable_ki6_frame_fix: true
      #sheet_reference_layout: pcb_print.kicad_wks
      scaling: 1.0
      pages:
        - layers: [ F.SilkS, Dwgs.User ]
          sheet: 'Top Silk layer'
        - layers: [ F.Mask, Dwgs.User ]
          sheet: 'Top Mask layer'
        - layers: [ F.Cu, Dwgs.User ]
          sheet: 'Top copper layer'
        #- layers: [ In1.Cu, Dwgs.User ]
        #  sheet: '1 inner layer'
        #- layers: [ In2.Cu, Dwgs.User ]
        #  sheet: '2 inner layer'
        #- layers: [ In3.Cu, Dwgs.User ]
        #  sheet: '3 inner layer'
        #- layers: [ In4.Cu, Dwgs.User ]
        #  sheet: '4 inner layer'
        - layers: [ B.Cu, Dwgs.User ]
          sheet: 'Bottom copper layer'
        - layers: [ B.Mask, Dwgs.User ]
          sheet: 'Top Mask layer'
        - layers: [ B.SilkS, Dwgs.User ]
          sheet: 'Bottom layer'
        - layers: [ F.Paste,Dwgs.User]
          sheet: 'Top paste Fabrication layers'
        - layers: [ B.Paste,Dwgs.User]
          sheet: 'Bottom paste Fabrication layers'
      output: "%v_%p_Rev%r-%i_%D.%x"



  - name: 'archiv'
    comment: "ZIP archive"
    type: compress
    dir: Produktion
    options:
      files:
        - from_output: gerbers
          dest: /
        - from_output: drill
          dest: /
      output: "%v_%p_Rev%r_%I.%x"
```
`
**Expected behavior**
variables defined by set_text_variables should be replaced and ${ISSUE_DATE}  should be replaced by current date 

**Screenshots**
SCH: 
![image](https://user-images.githubusercontent.com/120729391/211336517-80a54840-2e77-4a19-9ffb-7167acc60e68.png)
BRD:
![image](https://user-images.githubusercontent.com/120729391/211336685-790f3bab-70fe-4c5f-aef3-e687e200b397.png)

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? GitLab
- Using a docker image?`kicad_auto:dev_k6`

**Comment by set-soft** [comment] 2023-01-10 19:09
OK, I created a custom layout and tried it using KiCad. The ISSUE_DATE variable doesn't work in eeschema.
Solution: Use a variable defined by you.
For the PCB all works as spected, what is failing for you?
BTW: ISSUE_DATE is the date from the PCB, not the current date.
Pleas confirm the above, in this case this issue should be closed and a KiCad bug should be filled.

**Comment by MarkusSBS** [comment] 2023-01-11 08:38
ah sorry that i missed to explain it better 

I have some dummy data in the kicad projekt file for testing. 
For "erstellt durch" its Markus and "Genehmigt von" Its empty 

now i want to replace it with the git author and git commiter for a release. 
this is done with:   

```
set_text_variables:
    - name: 'SBS_Prj_Reviewer'
      command: 'git log -1 --pretty=format:"%cn"'
    - name: 'SBS_Prj_Creator'
      command: 'git log -1 --pretty=format:"%an"'

```

For the schematic everthing works as expected. Except the date is not set (but you mention i have to set it manualy) 

For the PCBnew nothing of the dummy data is replaced with the set_text_variables but the date is replaced with a dateformat i specifyed with:

```
global:
date_time_format: '%d.%m.%Y'

```

**Comment by MarkusSBS** [comment] 2023-01-11 15:17
i have done some more testing:

for ${comments1-9} it is not working, for any other text var of typ ${foo] it just works

**Comment by MarkusSBS** [comment] 2023-01-11 16:11
for the SCH i have tested to set the date by 

```
    - name: 'ISSUE_DATE'
      command: 'date -d @`git log -1 --format="%at"` +%d.%m.%Y'
```

the format is recognized by the PCB but not by the schematic 

hope that will help I am a little bit puzzled by this behaviour

**Comment by set-soft** [comment] 2023-01-11 16:35
Hi @MarkusSBS !
The variables replacement code passes various tests, so it works. Specific details could fail, but to identify them I need a test case that shows the particular situation.
Create a small project, doesn't have to be a real thing, just some project where the problem is exposed. Include the PCB, SCH, project and any WKS if needed. Also the KiBot file with only the needed things to show the problem.
You should also take a look at the debug information, looking for the variables you use (run KiBot with -vvvv).
I did a simple test with the files you sent and I got the SBS_Prj_Reviewer and SBS_Prj_Creator replaced.

Here is what I used: 
[#361.zip](https://github.com/INTI-CMNB/KiBot/files/10394264/361.zip)

**Comment by MarkusSBS** [comment] 2023-01-11 17:21
I wrote you an email with a test projekt

**Comment by set-soft** [comment] 2023-01-11 18:21
> for the SCH i have tested to set the date by
> 
> ```
>     - name: 'ISSUE_DATE'
>       command: 'date -d @`git log -1 --format="%at"` +%d.%m.%Y'
> ```
> 
> the format is recognized by the PCB but not by the schematic
> 
> hope that will help I am a little bit puzzled by this behaviour

Why are you trying to change a KiCad value. We already determined that `eeschema` fails to expand `ISSUE_DATE`, why you don't just define `MyDATE` and change your WKS to use `MyDATE`? This works for `eeschema`.
You can even use `DATE`, that you are defining in the KiBot file you sent me by e-mail.

For the other thing you mention about `commentN` please make a simple example, I don't have time to understand the details of your project.

**Comment by MarkusSBS** [comment] 2023-01-12 13:03
i have tryed to create a bare minimum projekt to reproduce the `commentN` problem  but i can not reproduce it with a new empty projekt. maybe just a problem with this specific projekt I have.

As recap:
`ISSUE_DATE` is just working for PCBnew, For the schematic it is brocken but it is named the same in the gui but not Logical connected. This is maybe a bug in KiCad. I had a  quick look into the KiCad source and the gui  for both are the same and both use something like GetDate but all of this handling differs drastically.

As Workaround:

1. Define a WKS with a specific textvar like Mydate and replace this in Kibot 
2. set a textvar into the pagesettings of eescheema and replace this in Kibot

sorry for all this truble its a quiet steep learning curve with this realy nice toolkit and all its features.

**Comment by set-soft** [comment] 2023-01-12 15:14
Hi @MarkusSBS !

> but i can not reproduce it with a new empty projekt. maybe just a problem with this specific projekt I have.

Can you write a recap for this particular issue? 

Looking at the files you sent me:
- You assign variable values to comment 1 to 9, like `${XXX_XXX}`
- They get expanded by KiBot

But I can't see where you use them. Your WKS doesn't use ${COMMENTn} or even %Cn (KiCad 5 style). I can't find them in the SCH or PCB. So I'm not sure if I understand what you want to do.

> sorry for all this truble its a quiet steep learning curve with this realy nice toolkit and all its features.

Is ok, I know fine tunning KiBot is complex. It currently supports a lot of things and a lot of them are workarounds to allow doing things that KiCad can't, which adds a lot of complexity.

**Comment by MarkusSBS** [comment] 2023-01-12 15:27
@

> But I can't see where you use them. Your WKS doesn't use ${COMMENTn} or even %Cn (KiCad 5 style). I can't find them in the SCH or PCB. So I'm not sure if I understand what you want to do.

for the last files i sended to you i have changed it to my own text var inside the WKS. 
Befor this i used a  custom wks with ${COMMENTn} and assembeld it with my text var in page settings. With this i had the problem that it was only replaced propperly in the schematic not the board.

I have tryed to replicate this behavior with a new projekt but i can not reproduce this problem. Maybe just user error and to obvius to reproduce it with the gained knowledge

**Comment by set-soft** [comment] 2023-01-12 15:51
Ok, I tried changing your WKS to use `${COMMENT2}` and it was replaced in both SCH and PCB, so it could be some simple error, like an extra space somewhere.

**Comment by set-soft** [comment] 2023-01-12 16:13
@MarkusSBS Thanks for supporting the project!

**Comment by set-soft** [comment] 2023-01-12 16:15
I'm closing the issue, if you find a way to reproduce the COMMENTx issue just open a new issue

**Closed by set-soft** 2023-01-12 16:15 UTC
Labels: needs more info

**Comment by set-soft** [comment] 2023-01-12 23:50
Just to clarify the main problem here:

The *ISSUE_DATE* variable is just what you input here:

![image](https://user-images.githubusercontent.com/22823627/212204112-af3ad7ba-4d7d-4e3b-9875-e47d12d62387.png)

This value is static and won't be updated. If the input box is empty the *ISSUE_DATE* will be replaced by nothing.
In order to get an updated value the user must avoid it and use some text variable, i.e. *DATE* 
Then you can simply update it using KiBot, like in the example discussed here:

```yaml
    - name: 'DATE'
      command: 'date -d @`git log -1 --format="%at"` +%d.%m.%Y'
```

You can't change the *ISSUE_DATE* using text variables because this is internally defined. KiCad uses the value found in the SCH/PCB file:

```lisp
  (title_block
    (date "2023-01-12")
  )
```

This value is copied by KiCad to *ISSUE_DATE*. When using KiBot internal drawings the value from the title block is processed using the global `date_time_format` option. KiCad outputs (like `pdf_sch_print`) know nothing about it and just copies the value from the title block.

This problem is solved using a text variable formated as we want.
